### PR TITLE
Fix building issue when compiling without debug

### PR DESCRIPTION
**Pull request by mwatterson**

### CODE REVIEW

**Comment by mwatterson** [comment]
Those asserts aren't the issue.  The problem is that there are statements like:
  const size_t sz = sizeof(T)*count;
  assert(fs_+pos_+sz <= sizeof(p_.payload));
Which throws an unused variable warning for sz, which is then raised to an error.

**Comment by versatran01** [comment]
That's why I suggest putting them in the `assert`.

**Comment by gareth-cross** [comment]
That will make the code harder to read. Instead I recommend defining an assert which evaluates to an empty function, which will prevent the unused warning and also avoid complicating the code.

**Comment by mwatterson** [comment]
Isn't that what assert is already?
Chao wants something like this:
    assert(
      const size_t sz = sizeof(T)*count;
      fs_+pos_+sz <= sizeof(p_.payload) 
    );
Which I think is decently readable.

**Comment by versatran01** [comment]
Oh, one thing that I might be missing is that, if the statement
```
decoder.advanceTo(FIELD_STATUS_REPORT)
```
has to be executed, then putting it in `assert` is not a good idea.
If that's the case, then maybe just add `-Wno-unused-variable` to the compiler flags.

**Comment by kartikmohta** [comment]
Adding -Werror (assuming that's the issue) is a bad idea in general anyway!

On Tue, May 19, 2015 at 12:05 PM, Chao Qu <notifications@github.com> wrote:

> Oh, one thing that I might be missing is that, if the statement
>
> decoder.advanceTo(FIELD_STATUS_REPORT)
>
> has to be executed, then putting it in assert is not a good idea.
> If that's the case, then maybe just add -Wno-unused-variable to the
> compiler flags.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KumarRobotics/imu_3dm_gx4/pull/10#issuecomment-103567680>
> .
>



-- 
Kartik

**Comment by gareth-cross** [comment]
Right, what I mean is there are cases where the values you want to check cannot be calculated in a single (or small number) of statements, but you still want to switch those off under certain build conditions. What I do is define a custom assertion which evaluates to an empty function under release mode - the compiler will strip the function but the unused warning is avoided.

**Comment by gareth-cross** [comment]
In response to @kartikmohta  I would say that adding -Werror enforces best practices - there is nothing wrong with this. Warnings are warnings for a reason - if you ignore them they can evaluate to runtime failures later. -Werror forces the developer to stop and solve the issue before moving on. Annoying at times, but a best practice in most cases, I would say.

**Comment by kartikmohta** [comment]
Yes, good practice for development, bad for release since a compiler version can add a new warning and then builds start failing.

**Comment by gareth-cross** [comment]
That is reasonable, but the default build mode is debug. We can add a flag which disables unused-variable warnings in release mode, which the user has to select willingly anyways in catkin - I prefer the default (debug) to remain as strict as possible.

**Comment by kartikmohta** [comment]
Yeah agreed on being strict but I hate the default mode being DEBUG for catkin build (due to cmake defaults)

**Comment by versatran01** [comment]
This is taking too long. 
u7I will close this pull request and remove -Werror, if everyone thinks this is ok.

**Comment by mwatterson** [comment]
My opinion is that you should just merge the fix, because just removing -Werror will make the code compile with warnings.

**Comment by versatran01** [comment]
Some `decoder.advanceTo()` are wrapped in those NDEBUG ifdefs, is it ok if they are not executed?

**Comment by gareth-cross** [comment]
Yea, line 667 of imu.cpp is incorrect. The advance variable exists only for debugging but the function call is necessary.

**Comment by mwatterson** [comment]
That explains why the imu wasn't running at the full rate.
 dababfd22459956bb82feb6a995234f903c6f8ca

**Comment by gareth-cross** [comment]
Just a personal opinion, but using the preprocessor to remove blocks of code is a bit more hazardous than using custom macros which enable/disable based on your build mode.

**Comment by yashm** [comment]
It's like you never left!

Giuseppe - care to say anything? :P

On Sun, Aug 16, 2015 at 2:30 PM, Gareth Cross <notifications@github.com>
wrote:

> Just a personal opinion, but using the preprocessor to remove blocks of
> code is a bit more hazardous than using custom macros which enable/disable
> based on your build mode.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KumarRobotics/imu_3dm_gx4/pull/10#issuecomment-131599013>
> .
>



-- 
|Y|
<http://www.yashmulgaonkar.com>
www.yashmulgaonkar.com

**Comment by versatran01** [comment]
I agree with @gareth-cross , using ifdefs is hazardous and inelegant.
I propose using `BOOST_VERIFY` to wrap around checks that need to be executed at all time and `BOOST_ASSERT` to warp around other checks.

**Pull request merged**
